# Generated by Django 4.2.3 on 2024-03-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SportPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("soccer", "Soccer"),
                            ("futsal", "Futsal"),
                            ("basketball", "Basketball"),
                            ("tennis", "Tennis"),
                            ("badminton", "Badminton"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position_name", models.CharField(max_length=50)),
            ],
        ),
    ]
