# Generated by Django 4.2.3 on 2024-03-25 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournamentmatch",
            name="away",
        ),
        migrations.RemoveField(
            model_name="tournamentmatch",
            name="home",
        ),
    ]
