# Generated by Django 4.2.3 on 2024-03-18 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0001_initial"),
        ("matchmaking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="away",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_matches",
                to="clubs.club",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_matches",
                to="clubs.club",
            ),
        ),
    ]
