# Generated by Django 4.2.13 on 2024-09-28 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sportsgrounds", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matchmaking", "0001_initial"),
        ("tournaments", "0001_initial"),
        ("leagues", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sportsgrounds.facilities",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="join_requests",
            field=models.ManyToManyField(
                blank=True, related_name="join_requests", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leagues.league",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="matches", to="matchmaking.teamplayer"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="referees",
            field=models.ManyToManyField(
                blank=True, related_name="refereed_matches", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="spectators",
            field=models.ManyToManyField(
                blank=True,
                related_name="spectated_matches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="sports_ground",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sportsgrounds.sportsground",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winning_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="matchmaking.winningmethod",
            ),
        ),
        migrations.AddField(
            model_name="groundreview",
            name="ground",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sportsgrounds.sportsground",
            ),
        ),
        migrations.AddField(
            model_name="groundreview",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="matchmaking.match"
            ),
        ),
        migrations.AddField(
            model_name="groundreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
