# Generated by Django 4.2.3 on 2024-03-25 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matchmaking", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FriendlyClubMatch",
        ),
    ]
