# Generated by Django 4.2.3 on 2024-03-25 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0001_initial"),
        ("matchmaking", "0002_delete_friendlyclubmatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchparticipant",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sports.sportposition",
            ),
        ),
        migrations.DeleteModel(
            name="SportPosition",
        ),
    ]
