# Generated by Django 4.2.3 on 2024-03-19 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matchmaking", "0002_alter_match_away_alter_match_home"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("soccer", "Soccer"),
                            ("futsal", "Futsal"),
                            ("basketball", "Basketball"),
                            ("tennis", "Tennis"),
                            ("badminton", "Badminton"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="matchparticipant",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="match",
            name="available_spots",
        ),
        migrations.AddField(
            model_name="match",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="matches", to="matchmaking.matchparticipant"
            ),
        ),
        migrations.AddField(
            model_name="matchparticipant",
            name="is_home_team",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="scorer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="matchmaking.matchparticipant",
            ),
        ),
        migrations.RemoveField(
            model_name="matchparticipant",
            name="match",
        ),
        migrations.AlterField(
            model_name="matchparticipant",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="matchmaking.sportposition",
            ),
        ),
    ]
