# Generated by Django 4.2.13 on 2024-09-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("leagues", "0001_initial"),
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstatistics",
            name="current_league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leagues.league",
            ),
        ),
    ]
