# Generated by Django 4.2.13 on 2024-09-28 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sportsgrounds", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("matchmaking", "0002_initial"),
        ("clubs", "0003_initial"),
        ("tournaments", "0001_initial"),
        ("accounts", "0003_initial"),
        ("newsfeed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstatistics",
            name="current_tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="userstatistics",
            name="previous_clubs",
            field=models.ManyToManyField(
                blank=True, related_name="previous_clubs", to="clubs.club"
            ),
        ),
        migrations.AddField(
            model_name="userstatistics",
            name="reviews",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="matchmaking.playerreview",
            ),
        ),
        migrations.AddField(
            model_name="userstatistics",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="playstyletest",
            name="user_statistics",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.userstatistics",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="owned_clubs",
            field=models.ManyToManyField(
                blank=True, related_name="owned_club", to="clubs.club"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="owned_sports_grounds",
            field=models.ManyToManyField(
                blank=True, related_name="owned_ground", to="sportsgrounds.sportsground"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_newsfeed",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_newsfeed",
                to="newsfeed.newsfeed",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
