# Generated by Django 4.2.3 on 2024-03-18 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matchmaking", "0001_initial"),
        ("newsfeed", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClubPost",
            new_name="MatchPost",
        ),
        migrations.DeleteModel(
            name="IndividualPost",
        ),
    ]
