# Generated by Django 4.2.3 on 2024-03-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsfeed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="custom_post_attachments/images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="VideoAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(upload_to="custom_post_attachments/videos/"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="custompost",
            name="content",
        ),
    ]
