# Generated by Django 4.2.3 on 2024-03-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsfeed", "0002_imageattachment_textattachment_videoattachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textattachment",
            name="text",
            field=models.TextField(max_length=200),
        ),
    ]
