# Generated by Django 4.2.3 on 2024-03-27 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("newsfeed", "0004_imageattachment_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custompost",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="custompost",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
