# Generated by Django 4.2.3 on 2024-03-16 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("newsfeed", "0001_initial"),
        ("matchmaking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualPost",
            fields=[
                (
                    "post_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="newsfeed.post",
                    ),
                ),
                ("scheduled_time", models.DateField()),
                ("match_time", models.DateTimeField(blank=True, null=True)),
                ("score", models.CharField(blank=True, max_length=50, null=True)),
                ("scorer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matchmaking.match",
                    ),
                ),
            ],
            bases=("newsfeed.post",),
        ),
    ]
