# Generated by Django 4.2.3 on 2024-03-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubgallery",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
