# Generated by Django 4.2.13 on 2024-09-28 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0002_initial"),
        ("tournaments", "0001_initial"),
        ("newsfeed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubstatistics",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="club_newsfeed",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_newsfeed",
                to="newsfeed.newsfeed",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="join_requests",
            field=models.ManyToManyField(
                blank=True,
                related_name="club_join_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="match_creators",
            field=models.ManyToManyField(
                blank=True,
                related_name="clubs_can_create_match",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="clubs_joined", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_club",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="owner_assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="clubs_can_assign_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="team_managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="clubs_can_manage_team",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
