# Generated by Django 4.2.13 on 2024-09-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("league_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "league_type",
                    models.CharField(
                        choices=[("club", "Club"), ("individual", "Individual")],
                        default="individual",
                        max_length=50,
                    ),
                ),
                ("total_number_of_rounds", models.IntegerField()),
                ("max_teams", models.IntegerField()),
                ("start_date", models.DateField()),
                ("deadline", models.DateField()),
                ("current_round", models.IntegerField(default=1)),
                (
                    "scheduling_type",
                    models.CharField(
                        choices=[
                            ("organizer_based", "Organizer Based"),
                            ("deadline_based", "Deadline Based"),
                        ],
                        default="organizer_based",
                        max_length=50,
                    ),
                ),
                ("match_duration", models.DurationField()),
                ("winning_method", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LeagueMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("match_date", models.DateField(blank=True, null=True)),
                ("match_time", models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeagueStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_position", models.IntegerField()),
                ("final_position", models.IntegerField(blank=True, null=True)),
                ("league_points", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("points_scored", models.IntegerField(default=0)),
                ("points_conceded", models.IntegerField(default=0)),
                ("matches_played", models.IntegerField(default=0)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leagues.league"
                    ),
                ),
            ],
        ),
    ]
