# Generated by Django 4.2.13 on 2024-09-28 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matchmaking", "0001_initial"),
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaguestatus",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="matchmaking.team"
            ),
        ),
        migrations.AddField(
            model_name="leaguematch",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_league_matches",
                to="matchmaking.team",
            ),
        ),
        migrations.AddField(
            model_name="leaguematch",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_league_matches",
                to="matchmaking.team",
            ),
        ),
        migrations.AddField(
            model_name="leaguematch",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leagues.league"
            ),
        ),
        migrations.AddField(
            model_name="leaguematch",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="matchmaking.match"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="participants",
            field=models.ManyToManyField(related_name="leagues", to="matchmaking.team"),
        ),
        migrations.AlterUniqueTogether(
            name="leaguematch",
            unique_together={("league", "match")},
        ),
    ]
