# Generated by Django 4.2.3 on 2024-03-26 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaguematch",
            name="away",
        ),
        migrations.RemoveField(
            model_name="leaguematch",
            name="home",
        ),
    ]
