# Generated by Django 4.2.3 on 2024-03-16 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("leagues", "0001_initial"),
        ("matchmaking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaguematch",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="matchmaking.match"
            ),
        ),
        migrations.AddField(
            model_name="leaguematch",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="leagues.leagueround",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leagueposition",
            unique_together={("league", "club")},
        ),
    ]
