# Generated by Django 4.2.3 on 2024-03-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0004_clubnewmemberpost"),
        ("leagues", "0002_remove_leaguematch_away_remove_leaguematch_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="clubs",
            field=models.ManyToManyField(related_name="leagues", to="clubs.club"),
        ),
    ]
